# Generated by Django 4.0.4 on 2022-05-06 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='اسم المستخدم')),
                ('email', models.CharField(max_length=255, verbose_name='البريد الالكتروني')),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
