# Generated by Django 4.0.4 on 2022-05-06 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
